### ISSUE TITLE
hydra a.fft

### ISSUE THREAD

**Issue by santoluigi** [munshkr/flok#110]

**Comment by munshkr** [comment]
How are you rrunning the flok server? I tried this with `flok-web` and it seems to work:

```javascript
a.show()

a.setBins(6)

osc(10, 0, () => (a.fft[0]*4))
  .out()
```

**Comment by santoluigi** [comment]
i do this:

cd flok/packages/web
yarn dev

after I go on chrome at http://0.0.0.0:3000/
I think the problem is that this page doesn't have any permission for use microphone and webcam
but I don't know how give it the permission

<img width="643" alt="Schermata 2021-04-23 alle 09 20 52" src="https://user-images.githubusercontent.com/37895574/115834334-66bf1780-a415-11eb-80e5-69cd624d1443.png">

**Comment by micuat** [comment]
@santoluigi you normally need https for mic/camera access for security reasons... but it should work if it's localhost

**Comment by santoluigi** [comment]
ok

with localhost://0.0.0.0:3000/ work good

thanks
