### ISSUE TITLE
problem with flok-repl -N nick

### ISSUE THREAD

**Issue by santoluigi** [munshkr/flok#111]
hi 

I've try to use flok in local server and when I try to connect there is an error with command -N

Last login: Thu Apr 22 14:54:07 on ttys000
gabrielepetrillo@MacBook-Pro-2 ~ % flok-repl -H ws://0.0.0.0:3000 -s Mjg5MGUzZTUtZjg3OS00OGNkLWI1NzEtZmNkODRmNDU3NGNk -t tidal -N gab --extra '{ "bootScript": "//Users/gabrielepetrillo/.cabal/store/ghc-8.8.4/tdl-1.6.1-3593a318/share/BootTidal.hs" }'
error: unknown option `-N'

**Comment by munshkr** [comment]
Hi! Can you try running `flok-repl -V` to see what version you have installed? I presume you have an old version. You can upgrade by running `npm install -g flok-repl`.

**Comment by santoluigi** [comment]
ok I've update folk-repl the version is 0.4.5. And seem to go...but when I try to do something in tidal for example:

d1 $ s "bd"

this is the error:

<interactive>:2:1: error:
    • Variable not in scope: d1 :: ControlPattern -> t
    • Perhaps you meant ‘dt’ (imported from Sound.Tidal.Context)

**Comment by santoluigi** [comment]
the problem was the version of tidal

i've installed the last version 1.7.4 and now work good
