### ISSUE TITLE
Include mercury-playground in web app?

### ISSUE THREAD

**Issue by tmhglnd** [munshkr/flok#125]
I was thinking it could be nice/interesting to include the mercury-playground (a stripped down version of Mercury that runs in the browser using Tone.js) in the Flok environment. But before starting to work on this I thought I'll ask what your opinion/thoughts are on this matter and if this is even something you would consider for the Flok environment. It will probably involve hosting the samples on the server as well (although not entirely sure if maybe there's another way). I'm currently hosting it on a glitch.com domain and will also move it to a paid version soon so it doesn't require the activate every time: https://mercury-sketch.glitch.me/. 

This is the repo: https://github.com/tmhglnd/mercury-playground, it is about 159mb. I could convert all the samples to .mp3, which will probably cut down the size quite a lot.

Curious what you think!

PS: If this is really not what you want for the environment don't worry! :) No pressure

**Comment by munshkr** [comment]
Hey! Yes, I really like the idea of letting flok be extended to as many languages/tools as possible! :-) 

I've been thinking for some time if it makes sense to have a "plugin" mechanism on the web server, separated in packages, so that if a user wants to host a flok instance, they can attach and configure other extensions, like the Mercury playground for example.

Besides that, I'm eager to add it to the instance running on flok.clic.cf, which is running on a cheap $5 DigitalOcean instance. I'm a bit scared of bandwidth consumption though, because of the samples. I should probably check the bandwidth limit on my instance.

**Comment by munshkr** [comment]
I'm guessing samples are lazily loaded if you use them, right? If that's the case, it should be probably be ok

**Comment by tmhglnd** [comment]
Awesome to hear that you are open to try this. The "plugin" mechanism sounds good as well, this will probably require me to make the playground into an npm package that is independent of the actualy front-end of the webpage that I currently have. Should not be to big of deal, I already have the parser in a seperate npm package too (https://github.com/tmhglnd/mercury-lang). 

At the moment all samples are loaded on load of the page into buffers. I choose this approach to make sure that while playing/performing buffers can be swapped near instantly when executing new code without having to wait for loading of new samples. I could try a different approach to see how that affects the performance.

**Comment by munshkr** [comment]
> Awesome to hear that you are open to try this. The "plugin" mechanism sounds good as well, this will probably require me to make the playground into an npm package that is independent of the actualy front-end of the webpage that I currently have. Should not be to big of deal, I already have the parser in a seperate npm package too (https://github.com/tmhglnd/mercury-lang).

Great, I think it'd be good to have at least the parser and audio engine as npm packages, that way it would be easy to upgrade them in the flok-web package later, if there are improvements or bugfixes. I can help you integrating them in flok then, if you want.

> At the moment all samples are loaded on load of the page into buffers. I choose this approach to make sure that while playing/performing buffers can be swapped near instantly when executing new code without having to wait for loading of new samples. I could try a different approach to see how that affects the performance.

That totally makes sense. I believe flok should then initialize Mercury's sound engine *only if* you create a session with at least one `mercury` target (or `mercury-web` maybe? To distinguish it from the original Mercury that works with the REPL...). That way, for users that won't use Mercury don't have to wait for loading samples.

**Comment by tmhglnd** [comment]
> I can help you integrating them in flok then, if you want.

Cool, not sure when I'll have time to get started but I'll keep you posted when the engine is ported to an npm package.

> That totally makes sense. I believe flok should then initialize Mercury's sound engine _only if_ you create a session with at least one `mercury` target (or `mercury-web` maybe? To distinguish it from the original Mercury that works with the REPL...). That way, for users that won't use Mercury don't have to wait for loading samples.

Yes, completely agree. I also had two separate targets in mind, just normal `mercury`, or `mercury-repl` and indeed something like `mercury-web` or `mercury-playground`, to clearly distinguish the two.

**Comment by tmhglnd** [comment]
Hey! Hope you're doing well! Re-opening this because I've been working on the `mercury-engine` (https://www.npmjs.com/package/mercury-engine) and I've been attempting to include the engine in the next.flok version. It's a bit unclear to me though how this should work. I've found files like the `use-xxxx.tsx` and `xxxxx-wrapper.tsx` for for example hydra and strudel, so I've been looking at those as a "template". Also found the `settings.json` where the webtargets are added it seems. But after doing all these steps I don't get a console.log that the wrapper is loaded (like with hydra and strudel). Do you have any pointers or clear guide on what would be the way to do this? Any help is appreciated!

I've been trying to make the engine as straight forward as possible. So right now you can just `require('mercury-engine')` and then create `const Engine = new Mercury()` and basically evaluate the code with `Engine.code()`. This works with basic html pages so I think it shouldn't be to difficult including it in Flok.

Last question is how to name the editor. I've named it `mercury-web` for now, since I would still like the `mercury` repl to still run and send code via osc to flok-repl. I was also considering naming it `mercury-playground` since that is how it's named on github. Or another option is just naming this one `mercury` and renaming the other one to `mercury-repl`. If you have an opinion on this than please let me know too.

**Comment by munshkr** [comment]
I guess in this case, you'd want to add a new `mercury-web` target, to differentiate it from the original `mercury` which uses the REPL, right?

**Comment by tmhglnd** [comment]
Thanks for the tips! I'll give this another look! One thing I ran into is that I created the engine as a `require()` library, not as a `module`, so it is not possible to use `import ... from ...`. Maybe I need to reconsider this if there is no other option to include the engine in Flok. Because using `require()` gives a building error `require is not defined`. Maybe there is some way in Vite to roll-up the requires in the distribution? I don't have experience with vite but I'll look into it as well.

Also I noticed that the strudel engine and hydra are loaded/initialized anyways, even if the editor is not used. I guess this will than also happen with Mercury if I follow the same approach. Is this desirable?

> I guess in this case, you'd want to add a new `mercury-web` target, to differentiate it from the original `mercury` which uses the REPL, right? Or is the REPL version deprecated?

Yes it's gonna be both, `mercury-web` and `mercury`, or I swap to `mercury` and `mercury-repl` but in any case both versions will still be running.

**Comment by tmhglnd** [comment]
Right now I've been able to get some working results if I `npm install --save-dev vite-plugin-require` and in `vite.config.ts` include `import vitePluginRequire from 'vite-plugin-require';` and under `plugins = []` run `vitePluginRequire.default()`. I created a `useMercury()` function that generates a `mercuryWrapper`. Then in `mercury-wrapper.tsx` I'm allowed to use `const { Mercury } = require('mercury-engine');`

I'm not sure however if this `vite-plugin-require` will have any downsides on the already existing other repls and the rest of Flok. I don't use any of the other languages so it's a bit hard to test for me. Hydra seems to work fine still tho.

In any case a promising first exploration. The engine also needs some updates anyways so don't think it's ready for a pull request just yet, haha.

**Comment by tmhglnd** [comment]
Hey! So i've been able to include the Mercury engine and all seems to work well! Since the samples need some time loading and the initialisation only happens on the first time code is evaluated i've included a warning message and skip the first eval. Than a message is shown when the engine is ready.

You can have a look in my fork here: https://github.com/tmhglnd/flok/tree/flok-next

My only issue is i'm not able to run the project in `npm run dev` mode anymore. I get an error from vite and I have not been able to find a way to fix it. When running `npm run build` and `npm start` everything works correctly. I would greatly appreciate if you can have a look and maybe have some ideas how to fix this issue.

The error i'm getting is: 
```
[plugin:vite-plugin-require] Unexpected token, expected "," (23:52)
/Users/timohoogland/Drive/work/code/js/flok/packages/web/src/main.tsx:23:52
21 |  ]);
22 |  
23 |  ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
   |                                                      ^
24 |    <React.StrictMode>
25 |      <HelmetProvider>
```

I've found a few ideas on [stackoverflow](https://stackoverflow.com/questions/72795666/how-to-fix-vite-build-parser-error-unexpected-token-in-third-party-dependenc) like adding `window.global ||= window;` to the top of `main.tsx` or adding `global: '({})'` to `vite.config.ts` but that didn't seem to do the trick just yet.
