### ISSUE TITLE
stdout of repl does not appear in browser view of session

### ISSUE THREAD

**Issue by jwaldmann** [munshkr/flok#136]
[EDIT] argh - this is #104

Hi. I am connecting "cat" as a repl. I am using the public server. When I send a text block (with Ctrl-Enter in the browser window), it does appear at the client, and is echoed:
```
node packages/repl/bin/flok-repl.js -H wss://flok.clic.cf -s Ym...... -n tidal -N cat -- cat

Hub address: wss://flok.clic.cf
Session name: Ym....
Target name: tidal
Type: command
Notify messages to user named "cat"
Extra options: {}
Spawn 'cat' with args: []
Connected to the server
[6cf2eac in ] wat
[6cf2eac out] wat
```
but - the echo is not shown in the browser. 

My actual use case is safe-tidal-cli for a private server, but the behaviour is exactly the same - no echo - but I need (error) messages from the repl to appear.

It worked fine a year ago. What changed?

What could I do to debug this on my own flok-web server instance?

**Comment by munshkr** [comment]
Hi! I changed the default behaviour of notifying all clients of every output from all REPL instances, to enable it again you have to pass the option `--notify-to-all`. Otherwise it will only send the output message to the user named `cat` (given by `-N`).

**Comment by jwaldmann** [comment]
Yeah I figured. It's working fine, I just forgot that we already discussed this.
