### ISSUE TITLE
problem with LocalServer

### ISSUE THREAD

**Issue by santoluigi** [munshkr/flok#148]
Hi, I have done everything that is written in the documentation:

I started the server with flock-web 

I started the REPL 

and everything works fine, the problem is when I want to connect another person. in fact, when I enter the REPL from the terminal (ex. flok-repl -h ws://192.168.0.5:3000 -t tidal -s 1a0c2df3-5931-46dd-9c7c-52932de15a5d) I see that he is connected, but how can he see and write on the editor? in fact, if I then pass him the link to insert on the browser (ex. http://192.168.0.5:3000) he is asked to start a new session and not to connect to mine. 

how do we connect to the same editor?

**Comment by munshkr** [comment]
Hi @santoluigi ! You should share him your *session URL*, which is the URL that you have on your browser tab when you create the session. In the example you mention, it would be something like: https://192.168.0.5:3000/s/1a0c2df3-5931-46dd-9c7c-52932de15a5d?layout=tidal,tidal,hydra 
If you are still not seeing each other, maybe there is a problem with your LAN or either one of you has a firewall and is blocking the connection. Let me know if that makes sense!
