### ISSUE TITLE
Public servers not working

### ISSUE THREAD

**Issue by alvarocaceresmunoz** [munshkr/flok#153]
I've been using the heroku public server for 1.5 months, creating a tidal session with Windows, and 2 Macs joining. The website has been throwing an error this week:
```
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
```

I can create and join sessions on https://flok.clic.cf/ from Windows. However, Macs see a blank page when they join (Firefox, Chrome, Safari)

Any ideas on what may be going on? We're trying to perform with a laptop ensemble next week and we wanted to keep using Flok for it.

**Comment by munshkr** [comment]
Hi! I'm afraid the heroku instance is no longer available (I was using a free instance but they stopped offering them for free recently), so the only public server right now is the one on https://flok.clic.cf

It should work on all platforms though. What browser are you using on your Mac? Could you try opening the Inspector console and see if there are any javascript errors?

**Comment by milangress** [comment]
@munshkr I don't know if it is related, but https://flok.clic.cf/ returns `502 Bad Gateway` for me 😢

**Comment by munshkr** [comment]
> @munshkr I don't know if it is related, but https://flok.clic.cf/ returns `502 Bad Gateway` for me cry

ouch, thanks for letting me know. It should be working now!

**Comment by milangress** [comment]
OMG! That was quick, thank you sooo much <3

**Comment by munshkr** [comment]
@alvarocaceresmunoz let me know if you're still having issues, will close for now.
