### ISSUE TITLE
flok-web parameter --static-dir not working

### ISSUE THREAD

**Issue by crcdng** [munshkr/flok#172]
to reproduce 

`npm install -g flok-repl flok-web`

`flok-web --static-dir <some-dir>` 

throws an error. 

```
ReferenceError: app is not defined
    at startServer (file:///Users/<username>/.nvm/versions/node/v19.5.0/lib/node_modules/flok-web/server.js:18:7)
```

After patching `Users/<username>/.nvm/versions/node/v19.5.0/lib/node_modules/flok-web/server.js
` with the missing line `const app = express();` the error is gone but serving from the directory still doesn't work. Serving from the default location (`/Users/<username>/.nvm/versions/node/v19.5.0/lib/node_modules/flok-web/dist`) works. 

To verify, put different images into the default location and the additional location and test with hydra:

```js
s0.initImage("http://localhost:3000/<myimage1>.png")
s1.initImage("http://localhost:3000/<myimage2>.png")
osc(6).modulate(src(s0),1).out(o0)
osc(6).modulate(src(s1),1).out(o1)
render()
```

MacOS, node v19.5.0

**Comment by munshkr** [comment]
Hey! Sorry for not responding earlier. I know it's been a long time, but I fixed a couple of things in the server last week. Feel free to reopen if this is still an issue.
