### ISSUE TITLE
strudel: speed is not a function

### ISSUE THREAD

**Issue by felixroos** [munshkr/flok#182]
probably because there is a name collision with hydra?

**Comment by tmhglnd** [comment]
I now also see during the Livecodera livestream that Strudel is having a hard time with the `m` value that we made global for connecting sound from Mercury to Hydra. In the jam they are trying out now (with mercury, hydra and strudel panels) Strudel keeps throwing the error: `TypeError: m is not a function`

**Comment by munshkr** [comment]
These global variable issues should be fixed now :)
