### ISSUE TITLE
When creating a new session, it should stop all web targets in the session (hydra, strudel, mercury etc.)

### ISSUE THREAD

**Issue by munshkr** [munshkr/flok#193]
Probably the easiest and safest way to unload and start anew is to fully refresh the session page, so that global variables are also cleaned up (at least until #239 is addressed)

**Comment by tmhglnd** [comment]
This should the probably also do the same for `mercury-web`?

**Comment by munshkr** [comment]
You're right! I copied this issue title from a Trello I was using some
months ago. I should actually stop all web targets.
