### ISSUE TITLE
No matching version flok-repl alpha.10

### ISSUE THREAD

**Issue by tmhglnd** [munshkr/flok#205]
Hey! 

Currently the repl configuration shows `flok-repl@1.0.0-alpha.10`, but when I run this I get: `npm ERR! notarget No matching version found for flok-repl@1.0.0-alpha.10.`

I see on npmjs.com that the latest alpha was `.6`, I tried using that and it works again fine. Should I continue using that or should there be a `.10` but it is not published to npm?

**Comment by munshkr** [comment]
Ah yes sorry for the confusion, I tried to fix something earlier today but
cancelled midway because I found another bug. Just use alpha.6 for now,
I'll fix this soon.

**Comment by tmhglnd** [comment]
Alright, good to know! Thanks
