### ISSUE TITLE
Sharing a Flok session link that already has targets sometimes pops-up "Configure Layout"

### ISSUE THREAD

**Issue by tmhglnd** [munshkr/flok#214]
Hey!

When I share a link to a flok session that already has one or more targets and open it in a private browser window it prompts with the "configure layout" message asking for a list of targets. If you accidentally click save it removes the unused panels and goes back to a default hydra panel...

I think this prompt should be disabled when panes are added and include some code already. Especially to avoid confusion or people accidentally removing things.

Steps to reproduce:
1. Create new session in the browser (i'm using Brave), add 2 or more targets (eg. mercury-web, hydra)
2. Add some code/text to both targets just to have something there
3. Copy flok link and open in a private browser window (for Brave is shift+cmd+n) and paste
4. It prompts the "configure layout" panel, and when you click save the mercury-web is removed

**Comment by munshkr** [comment]
Hey, thanks for reporting this, I noticed this bug yesterday too... I'll take a look later today!

**Comment by tmhglnd** [comment]
If I'm honest I liked the simplicity of just opening flok and not getting this prompt but just selecting the editor from the drop-down menu. But i'm also fine having this feature so no worries of course haha! Great work in any case!

**Comment by munshkr** [comment]
It should *only* show up if it's a new session, so in your case it shouldn't appear... Or you mean you liked it better when it used hydra by default?

**Comment by munshkr** [comment]
I also liked it better before, but it was confusing for newcomers. Maybe I can add a checkbox like "do not show again on new sessions"?

**Comment by tmhglnd** [comment]
>Or you mean you liked it better when it used hydra by default?

Yes just hydra default and I just clicked the drop-down menu for mercury-web.



> I also liked it better before, but it was confusing for newcomers. Maybe I can add a checkbox like "do not show again on new sessions"?

I see! Okay I'm fine keeping the configuration panel when it is a new session, no problem! 



> Hmm there's another bug, if you cancel the dialog or click elsewhere, the session has no documents 😵‍💫

Ah, yes! Well at least you can still add a panel from the menu hehe! But yes makes sense it defaults to hydra again if you don't click anything. (or some other editor, but maybe hydra is the most used in flok, i don't know? maybe it should be random if you don't decide, try something new haha)

**Comment by munshkr** [comment]
Ok, I've added a Welcome dialog that shows only once, and I've hidden the Configure dialog, so basically it behaves as before: it immediately starts with a hydra slot

**Comment by tmhglnd** [comment]
Looks good to me!
