### ISSUE TITLE
Strudel loads twice

### ISSUE THREAD

**Issue by tmhglnd** [munshkr/flok#259]
When starting Flok the console shows:

```
index-rGOb6-ww.js:4365 @strudel/core was loaded more than once...
This might happen when you have multiple versions of strudel installed. 
Please check with "npm ls @strudel/core".
```

Not sure if this can cause any issues?

**Comment by munshkr** [comment]
Does not seem to be an issue, but I upgraded the Strudel packages to 1.0.1 and it stopped complaining.
