### ISSUE TITLE
Have a way to share JS variables between languages (hydra, mercury-web, strudel)

### ISSUE THREAD

**Issue by munshkr** [munshkr/flok#272]
Now that we're using iframes to isolate the JS context of each language, they won't share the same `window` for globals.

**Comment by tmhglnd** [comment]
Can this be fixed by calling `parent.varname` to store from the iframe to the global `window.`? And use `parent.varname` to get the value from the global window in another iframe? Haven't tried yet.

**Comment by munshkr** [comment]
> Can this be fixed by calling `parent.varname` to store from the iframe to the global `window.`? And use `parent.varname` to get the value from the global window in another iframe? Haven't tried yet.

Yes, I was thinking exactly that. If we define something like `window.parent.mercury = window;` inside the mercury page, hydra could access it via `parent.mercury.m` for instance. It's uglier than before, but at least there's no way chance of name clashing this way...
Maybe this can be improved by avoiding the parent and defining a `mercury` global in hydra context.

**Comment by tmhglnd** [comment]
Yeah, one concern I have is the amount of typing in the Hydra code eventually. Now it is nice and concise like: 

`osc( () => m ).out()`

But maybe it is still possible to have in hydra a global `window.m = parent.mercury.m`? That way we keep it working it was before.

**Comment by munshkr** [comment]
> Yeah, one concern I have is the amount of typing in the Hydra code eventually. Now it is nice and concise like:
> 
> `osc( () => m ).out()`
> 
> But maybe it is still possible to have in hydra a global `window.m = parent.mercury.m`? That way we keep it working it was before.

done

**Comment by tmhglnd** [comment]
Yes! Looks like everything works as it should!
