### ISSUE TITLE
[strudel] AudioWorklet based effects don't work anymore

### ISSUE THREAD

**Issue by felixroos** [munshkr/flok#286]
using strudel effects that internally use AudioWorklets don't work anymore and result in silence:

```js
s("bd*4").shape(.4)
```

this is the case for `coarse`, `crush`, `shape` (and `dist`, `supersaw` in the soon to be released version)
getting:

```
[cyclist] error: Failed to construct 'AudioWorkletNode': AudioWorkletNode cannot be created: AudioWorklet does not have a valid AudioWorkletGlobalScope. Load a script via audioWorklet.addModule() first.
```

This seems to be happening since https://github.com/munshkr/flok/commit/205232cd6d968750c8c4daff58bbb9395ae981d3 was added. Not sure what the exact problem is, maybe `initAudioOnFirstClick` is called in the wrong place?

**Comment by lukaprincic** [comment]
these strudel effects would be so good to have in flok!

**Comment by munshkr** [comment]
Found a workaround: When loading, if you click somewhere outside the editor pane, it will call the click event added by `initAudioOnFirstClick`, effectively initializing the audio worklet:
<img width="291" alt="image" src="https://github.com/user-attachments/assets/18d8fea5-24ba-43cd-b52e-66b4f4ac41fe">

**Comment by munshkr** [comment]
@felixroos @lukaprincic I think it's working now :)

**Comment by lukaprincic** [comment]
wow, thank you so much!!
