### ISSUE TITLE
evaluation flash gets stuck sometimes

### ISSUE THREAD

**Issue by felixroos** [munshkr/flok#296]
I've noticed the flash on evaluation gets stuck sometimes, maybe just for strudel, maybe also only with multiple evaluations happening in parallel.
It usually goes away on the next evaluation, so not super annoying. 

I haven't looked at the code but i'd speculate the timeout to unflash gets canceled for some reason. might also be related to multiple timeouts happening at the same time (when multiple people evaluate in parallel)

**Comment by tmhglnd** [comment]
I have noticed this some time ago as well.
