### ISSUE TITLE
No module named 'FoxDot.lib'

### ISSUE THREAD

**Issue by diegomolinaquintero** [munshkr/flok#50]
I am a novice and it is probably my mistake but when I follow the instructions to run foxdot I get this 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/XXXX/FoxDot/__init__.py", line 120, in <module>
    from .lib import *
ModuleNotFoundError: No module named 'FoxDot.lib'

Which version of Python do you recommend?

**Comment by munshkr** [comment]
Currently Flok tries to run FoxDot using `python3`, but it appears you don't have FoxDot installed there. Can you try running `pip3 install FoxDot`?

Nonetheless, the REPL should use `python` by default, and if a user wants to specify a different Python executable, you should be able to set it as an extra option.

**Comment by diegomolinaquintero** [comment]
Ya soluciones , era un descuido ... Estaba ejecutando el flok Rep  -t foxdot por fuera de la carpeta de.foxdot , cuando la ejecute adentro funciono perfecto en Mac ... Lo probé en arch Linux y todo funcionó perfecto . Tengo una inquietud los que usan hydra no pueden escuchar nada a menos que ejecuten foxdot ? O hay otra forma

**Comment by munshkr** [comment]
Genial! Sí, cualquier usuario que quiera escuchar el sonido, tiene que levantar FoxDot (y ejecutar SuperCollider). No hace streaming de audio ni síntesis en el browser.
