### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by jwaldmann** [munshkr/flok#55]
Hi. 

I came here from https://forum.toplap.org/t/what-is-this-editor-for-live-collaboration/1224

the README suggests "simply run `flok-web`" but that isn't working - of course, as there is no such thing in my `$PATH`. I would have been more surprised if it did work.

I did `npm install flok-web flok-repl` as suggested (but without `-g`, to keep my global state sane). During install, I see some warnings. (Which I ignore, because it says warning, not error...)

Then this seems to work (at least ist starts):
```
./node_modules/.bin/flok-repl 
Missing REPL command (e.g.: flok-repl -- cat)
Usage: flok-repl [options]
```
but this does not:
```
./node_modules/.bin/flok-web 
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/home/waldmann/software/music/flok/node_modules/flok-web/.next/prerender-manifest.json'
```
This is on Fedora GNU/Linux with node v12.16.2 npm 6.14.4

**Comment by jwaldmann** [comment]
Ah I got it now. I will leave this here as it may be helpful for others:

* install `yarn`, see https://developer.fedoraproject.org/tech/languages/nodejs/nodejs.html or build from source
```
mkdir yarn ; pushd yarn ; npm install yarn ; popd
```
* build flok
```
cd flok; ../yarn/node_modules/.bin/yarn install
```
* then use
```
node packages/web/bin/flok-web.js
node packages/repl/bin/flok-repl.js
```

**Comment by munshkr** [comment]
Hi!

Thanks for the report. Glad you made it work. I haven't really tried installing locally (without the `-g` option), I'll check later about that error.
