### ISSUE TITLE
browser shows "An unexpected error has occurred."  when WebGL is not enabled

### ISSUE THREAD

**Issue by jwaldmann** [munshkr/flok#56]
When I point my browser to a running server, the start screen appears briefly, but then "An unexpected error has occurred."

In Firefox/Web Console I found
```
THREE.WebGLRenderer: Error creating WebGL context.
```
Of course I have webgl disabled (https://restoreprivacy.com/firefox-privacy/) and it's not obvious that flok needs it. Could you perhaps state that it's (currently) needed (in the README, in the error message)?

**Comment by munshkr** [comment]
It should be optional. There are two instances where WebGL is used:

1. The index page (`/`), which loads a 3D scene as background
2. The session page (`/s/{uuid}`), where Hydra is loaded, which uses WebGL.

As you state, if WebGL is disabled, it should warn the user (only in the session page, the index scene is completely aesthetic) and keep going, not crash.
