### ISSUE TITLE
--redirect-https gives SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by jwaldmann** [munshkr/flok#57]
I am starting the server:
```
./packages/web/bin/flok-web.js  -P 8000 --redirect-https
> Going to redirect http to https
> Listening on http://0.0.0.0:8000
```
When connect to that port with firefox (75.0), the redirect happens (the address bar shows "https://" but then I get
```
Error code: SSL_ERROR_RX_RECORD_TOO_LONG
```
(I checked that it's working without "--redirect-https", so it's not #56 )

**Comment by munshkr** [comment]
Yes, this happens because currently the web server is not serving content with SSL. On the public servers I solved this with nginx, but #28 should fix this.

**Comment by munshkr** [comment]
I've just removed this option, and added `--secure/-s` for serving through https for local networks.

**Comment by jwaldmann** [comment]
> On the public servers I solved this with nginx,

How exactly?

I am running flok-web with `-H localhost -P 8000 -s`
and have nginx redirect   `/` to `https://localhost:8000/` .
I can connect several browser sessions to `https://my-public-address`
and the shared editing works.

but I cannot attach a remote flok-repl, using `wss://my-public-address`:
```
unable connect to the server Error: Unexpected server response: 404
    at ClientRequest.<anonymous>
```
When I connect a client that runs on the same machine (so, using `wss://localhost:8000`) I am not getting this error, and the server log shows that the client is connected. but then it seems that nothing gets sent on Ctrl-Enter.

**Comment by munshkr** [comment]
If you start `flok-web` with `-P 8000`, the WebSocket server will also listen on port 8000, so I think you should connect flok-repl with `-H wss://my-public-address:8000`.

On my public server (https://flok.clic.cf) I configured nginx to serve flok-web normally (through http at port 3000, that is, without `--secure`), and used [certbot](https://certbot.eff.org/) from Let's Encrypt to tell nginx to 1) redirect from http to https, and 2) serve https itself.

This is the current nginx configuration:

```
server {
    server_name flok.clic.cf;

    location /_next/static/ {
        alias /home/munshkr/flok/packages/web/.next/static/;
    }

    location / {
      # default port, could be changed if you use next with custom server
      proxy_pass http://localhost:3000;
    
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
      
      # if you have try_files like this, remove it from our block
      # otherwise next app will not work properly
      # try_files $uri $uri/ =404;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/troop.clic.cf/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/troop.clic.cf/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = flok.clic.cf) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name flok.clic.cf;
    listen 80;
    return 404; # managed by Certbot
}
```

Maybe you can use something similar. Do you have a domain registered to that ip address, or are you connecting directly to that address?

**Comment by munshkr** [comment]
> If you start `flok-web` with `-P 8000`, the WebSocket server will also listen on port 8000, so I think you should connect flok-repl with `-H wss://my-public-address:8000`.

Now I'm thinking that should have that port open to access it from outsite... not ideal. I think it's better to use something like the nginx configuration I pasted above.

**Comment by munshkr** [comment]
Can you paste your nginx configuration? Maybe there's something missing? It should redirect the websockets connection, now that I'm thinking...

**Comment by jwaldmann** [comment]
Your nginx config works for me (`flok-web -H localhost`, `flok-repl -H ws://localhost:3000`). Thanks!
