### ISSUE TITLE
browser creates high CPU load for rendering the GUI client page

### ISSUE THREAD

**Issue by jwaldmann** [munshkr/flok#60]
When my browser (firefox) renders tha GUI client page, I am typically seeing
100 percent load:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  12621 waldmann  20   0 3226484 382292 165596 R  94.1  10.2  10:59.76 firefox
  12707 waldmann  20   0 3186668 473352 196820 R  47.1  12.6  33:46.79 Web Content
```
even if nothing is happening (no-one edits). Is this expected? Perhaps related to #56 (webgl)

When I open Firefox->Tools->Performance, I am seeing a lot of `requestAnimationFrame` but I really don't know how to read those charts/graphs.

Same with chromium
```
  15124 waldmann  20   0 4893160 196512 143784 S  77.8   5.2   1:58.95 chromium-browse
  14916 waldmann  20   0  727692 277096 142352 S  22.2   7.4   2:38.85 chromium-browse
```
this is on a somewhat dated computer that apparently has no "hardware acceleration" (at least, when I switch this flag in chromium, nothing changes)

**Comment by munshkr** [comment]
Thanks for debugging this. I noticed it too, but didn't know that it still happened even when there are no edits! It's probably related to the Hydra canvas component.

**Comment by jwaldmann** [comment]
I found that the CPU load is high as described only when the browser window is visible.
It goes down (to 10 percent) as soon as I switch to another (virtual) desktop.

**Comment by munshkr** [comment]
I tested removing the Hydra component and the CPU load goes down considerably. I'm not sure if there's something I could to do to improve that here. The least we could do is let the user enable or disable Hydra when entering a session (re #47).

For now, I've made that Flok doesn't load the Hydra component if there is no "hydra" target on the session.

**Comment by jwaldmann** [comment]
Great! I confirm that load is very low now, for a GUI client with a `tidal` session, and I didn't need webgl enabled in the browser.

**Comment by munshkr** [comment]
Awesome! I'll close this for now then.
