### ISSUE TITLE
contents of a session vanishes when last web client leaves

### ISSUE THREAD

**Issue by jwaldmann** [munshkr/flok#62]
I was running a session with  one repl client, and one web client. There was some text in the buffer (and the repl was playing it via tidal).

When I closed the web client, and opened another one, with the sessions's address, I found that the session still exists  but its text buffer was empty. I expected it to show the previous contents.

The repl kept working all the time - I could send commands to it from the new web client.

I confirmed that with one web client constantly running, a second one could leave and join and see the previous text.

**Comment by munshkr** [comment]
Yes, this happens when you are the only client connected. State is preserved only between peers. When a new user connects, it asks for the document's content to another user. I thought of storing content automatically on local storage (see #38) to mitigate this issue.

**Comment by munshkr** [comment]
Fixed this using local storage.

**Comment by jwaldmann** [comment]
awesome - I will test this (and https) as I have an online live coding collab seminar coming up this week.

**Comment by jwaldmann** [comment]
Hi. What is the status here - what does flok do when the last web client of a session vanishes - and a repl client is still connected?

**Comment by munshkr** [comment]
Flok now uses three Yjs backends (Yjs is the collaborative editing library for syncing changes between peers), in order: webrtc, websockets and localstorage. As I understand it, before leaving the web page, it should keep it stored on localstorage, so when entering again you will see the latest content. Is it not working?

**Comment by jwaldmann** [comment]
I am not sure, see #102 .

**Comment by munshkr** [comment]
You can check this with yourself (one user), if you write something and refresh the page, it should bring back what you last wrote (because it synced from local storage).
