### ISSUE TITLE
is there a "dumb" repl mode? how to connect repl?

### ISSUE THREAD

**Issue by jwaldmann** [munshkr/flok#64]
I am experimenting with an alternative repl (  https://github.com/jwaldmann/safe-tidal-cli )

So I have an executable that reads stdin (coming from the server) and writes to stdout and stderr (I want to send that to the server, so that GUI clients see it)
* how do I specify the pathname of the executable?
* what is the interface that the executable must implement? (How I know that a text block is finished?)

`flok-repl.js -h` suggests `--list-types` which all seem to have specific semantics. I don't want any (e.g., no `:{`  `}:`. Just give me blocks of text.)

The help text also suggests `flok-repl -- cat`
so I am trying that but I am not seeing anything echoed.

When I put the name of my repl: ` ... -- safe-tidal-cli`, it gets started, but does not seem to be connected.

**Comment by munshkr** [comment]
> When I put the name of my repl: ... -- safe-tidal-cli, it gets started, but does not seem to be connected.

You also have to pass the host, session name and target name. By default, the host is "localhost", and the target name is "default", if not provided (maybe it should be called the same as the command, like "safe-tidal-cli"?)

For example, if your session token is `ZGE3ZTZlOTktMTYxMS00Y2EwLTlmNzYtMGE1Zjk0NTE2N2Uz`:

```
flok-repl -s ZGE3ZTZlOTktMTYxMS00Y2EwLTlmNzYtMGE1Zjk0NTE2N2Uz -n tidal -- safe-tidal-cli
```

**Comment by munshkr** [comment]
btw safe-tidal-cli looks interesting!

**Comment by jwaldmann** [comment]
Ah, I think I was missing `-n tidal`. Also, the `-h` text should mention `-- <exec>`? I am working on my repl now.

**Comment by munshkr** [comment]
Great! I fixed this on 4848629da49e67f885c57dca90523267e3e4bfbc

**Comment by jwaldmann** [comment]
Hi. Does this still work? I am trying
```
node packages/repl/bin/flok-repl.js -H wss://localhost:8000 -s mytoken -n tidal   -N JW -- cat
```
but this gives me
```
Hub address: wss://localhost:8000
Session name: mytoken
Target name: tidal
Type: command
Notify messages to user named "JW"
Extra options: {}
Spawn 'undefined' with args: []
internal/validators.js:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at normalizeSpawnArguments (child_process.js:406:3)
    at Object.spawn (child_process.js:546:13)
    at CommandREPL.start (/home/waldmann/software/music/flok/packages/repl/lib/repl.js:55:37)
    at Object.<anonymous> (/home/waldmann/software/music/flok/packages/repl/bin/flok-repl.js:124:12)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

**Comment by munshkr** [comment]
That's a bug, will look into it.

**Comment by jwaldmann** [comment]
Thanks, I appreciate it. I am planning to use flok in a lecture later this week. (So I should have started testing somewhat earlier, but you know how it is ...) If you don't find the time to debug - could you tell me where to look in the source?

**Comment by munshkr** [comment]
@jwaldmann I think I fixed it now, can you try again? Do you need me to push a new version or are you using the cloned repo?

**Comment by jwaldmann** [comment]
Using cloned repo. Test with "cat" works, so I assume it'll be fine with my repl - will test this later. 

Thanks very much!

**Comment by jwaldmann** [comment]
OK - works with my repl.
