### ISSUE TITLE
Cannot find module prerender-manifest.json

### ISSUE THREAD

**Issue by pl-gauthier** [munshkr/flok#66]
Just installed flok on a fresh upgrade of Arch Linux using : 

`npm install -g flok-repl flok-web`

But when starting `flok-web` I get : 

`Error: Cannot find module '/usr/lib/node_modules/flok-web/.next/prerender-manifest.json'`

Complete output bellow :
[https://termbin.com/baae](https://termbin.com/baae)

Can I provide anything else to help along ?

**Comment by munshkr** [comment]
Thanks for reporting this. It's a bug in the published release of `flok-web`. I'll try to fix it later today.

**Comment by munshkr** [comment]
Fixed in latest version (0.3.13)

**Comment by pl-gauthier** [comment]
Thanks a lot !
