### ISSUE TITLE
Couldn't process unknown directive 'report-to'

### ISSUE THREAD

**Issue by jwaldmann** [munshkr/flok#71]
A user reports that when they Ctrl-Enter in the editor, they get
```
Content Security Policy: Couldn't process unknown directive ´report-to´
...
unknown message type: pong
```
with Firefox 68.8.0esr (64-bit) and Chromium 80.0.3987.162 both from debian-buster.

**Comment by munshkr** [comment]
Do you remember if it failed to evaluate the code when the user hit Ctrl+Enter?
I think that CSP message is just a warning, but not 100% sure.

The "unknown message type: pong" is harmless too, I've just removed it though so it shouldn't show up anymore.

**Comment by munshkr** [comment]
Will close. Feel free to reopen.
