### ISSUE TITLE
ERROR:webrtc_sdp.cc(402)] Failed to parse: ""

### ISSUE THREAD

**Issue by jwaldmann** [munshkr/flok#72]
When I connect chromium to a flok session, I am seeing some
```
[.....:ERROR:webrtc_sdp.cc(402)] Failed to parse: "". Reason: Expect line: candidate:<candidate-str>
```
since it mentions `webrtc` it might be related to flok. But the behaviour of the editor seems normal.

**Comment by munshkr** [comment]
That's weird, I haven't seen that error. Do you know which chromium version is that from?

**Comment by munshkr** [comment]
Will close. Feel free to reopen.
