### ISSUE TITLE
duplicate text in editor

### ISSUE THREAD

**Issue by jwaldmann** [munshkr/flok#73]
(not reliably reproducible but perhaps you have seen this before) 

We are sometimes getting duplicate text in the editor window: When a new client joins (?), a full copy of the present text is appended.

**Comment by munshkr** [comment]
I think I broke this on commit 6c051b4e206183c47fedabe6a5f79039e34d9385 because of race conditions.

Will be fixing it ASAP.

**Comment by munshkr** [comment]
Done. I had to revert that commit, that problem was harder to solve than I thought...
