### ISSUE TITLE
installation on ubuntu 20.04, immediate failure of web interface

### ISSUE THREAD

**Issue by ekg** [munshkr/flok#79]
I've installed flok on ubuntu 20.04, using node 12.

```
-> % npm --version
6.14.5
-> % node --version
v12.18.2
```

When I run flok-web, then access it via brave, I get "An unexpected error has occurred."

I then installed tidal, and attempted to connect flok-repl to to the session to resolve the problem.

```
flok-web &
flok-repl -t tidal
```

But this does not change the result.

Am I missing a basic step in the installation and setup? I'd like to try this locally.

**Comment by munshkr** [comment]
Hi! When you run `flok-web`, does it say this?
```
$ flok-web
> Listening on http://0.0.0.0:3000
```
I haven't tried with Brave, but if you go to https://flok.clic.cf/, does it work there?

**Comment by ekg** [comment]
It does say that it's running (exactly the same as you shared). I can use it on the website you posted on the same browser where the npm installed version breaks.

Should I install from git? What's the procedure to do so?

**Comment by munshkr** [comment]
> It does say that it's running (exactly the same as you shared). I can use it on the website you posted on the same browser where the npm installed version breaks.

Really weird, I tried with Brave too here, but looks fine.

> Should I install from git? What's the procedure to do so?

https://github.com/munshkr/flok#development
You will need to install [Yarn](https://yarnpkg.com/), then after cloning the repository, run `yarn` to install dependencies, and `yarn dev` to start the server.

**Comment by jwaldmann** [comment]
> You will need to install [Yarn](https://yarnpkg.com/), then ...

cf. https://github.com/munshkr/flok/issues/55#issuecomment-612613622

**Comment by munshkr** [comment]
Thanks @jwaldmann - you can also install yarn with your package manage probably (see https://classic.yarnpkg.com/en/docs/install/#debian-stable), but that solution works if you don't want to install globally.

I really should build portable binaries to download, both for the repl and the web server...

**Comment by ekg** [comment]
Is it possible to use node 14, or only 12?

**Comment by ekg** [comment]
I've built from git, using yarn. I get the same error on brave, but I don't get it on firefox. It's definitely browser-related then.

For the record, this is my brave version:

```
-> % brave-browser --version
Brave Browser 81.1.9.80 
```

I'm running a few extensions that have access to the page, but turning them off didn't seem to make any difference.

**Comment by munshkr** [comment]
Sorry for the late reply...

> Is it possible to use node 14, or only 12?

Last time I checked, Hydra didn't work correctly on node 14 because of a dependency, but this might have changed...

> I've built from git, using yarn. I get the same error on brave, but I don't get it on firefox. It's definitely browser-related then.
> 
> For the record, this is my brave version:
> 
> ```
> -> % brave-browser --version
> Brave Browser 81.1.9.80 
> ```
> 
> I'm running a few extensions that have access to the page, but turning them off didn't seem to make any difference.

I forgot to ask this: did you try using `yarn dev` or `yarn start`? (the first one starts a develoment server, the latter builds an optimized version, so maybe something is wrong there)

**Comment by munshkr** [comment]
I assume it's the same issue reported on https://github.com/munshkr/flok/issues/86
It's a problem with the npm built package, I'm looking into it.

**Comment by munshkr** [comment]
I'll close this for now as the issue at #86 was resolved. If you happen to try again and it still fails feel free to reopen. Thanks!
