### ISSUE TITLE
TypeError: Cannot read property 'getTexture' of undefined

### ISSUE THREAD

**Issue by zackkrida** [munshkr/flok#90]
On https://flok.clic.cf/, the following snippet doesn't work, but _does_ in Hydra:

```js
s0.initCam()

src(s0).layer(src(s0).scrollY(() => time).saturate(5).luma()).out()
```

Results in a `TypeError: Cannot read property 'getTexture' of undefined` error.

Here's hydra and flok side by side:

<img width="2560" alt="Screen Shot 2020-11-20 at 2 37 19 PM" src="https://user-images.githubusercontent.com/6351754/99862498-0a8e5980-2b3e-11eb-9b2a-3481241d9297.png">

**Comment by munshkr** [comment]
Hi! thanks for reporting, I've tried this just now, and it seems to work, maybe something else caused the problem? I feel like I've seen this error once, will have to investigate a bit.

**Comment by zackkrida** [comment]
yes, works fine today. cool 👍 
maybe the error was prompted by some other previously-executed code or something—i'll try to provide more detail if i encounter it again!

**Comment by munshkr** [comment]
I'll close this. Feel free to reopen if it happens again (I suspect it is a Hydra bug though).
